version: '3.9'

services:
  db:
    image: ankane/pgvector:latest
    container_name: face-recognition-postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: face_recognition
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  fastapi_app:
    build: .
    container_name: face-recognition-fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env  # Load environment variables from .env
    ports:
      - "4003:4003"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "4003", "--reload"]

volumes:
  postgres_data:
